### ISSUE TITLE
【依頼】フリマアプリの挙動確認

### ISSUE THREAD

**Issue by 500ban** [iniwa-takaya/furima-35690#9]
# URL
https://furima-35690.herokuapp.com/
# Basic認証
id: admin, password: 1234
# 出品者
email: test1@test.com password: a12345
# 購入者
email: test2@test.com password: a12345

**Comment by snkw-works** [comment]
@iniwa-takaya さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/119945646-b4a8db80-bfd0-11eb-9854-b5513dc1baf2.png)
